package mcvandfileservice;

import java.time.Duration;
import java.util.List;

import schedules.Schedule;
import schedules.WeeklyTimeBlock;

/**
 * Lead Author(s):
 * @author Selena Niedbalski
 * 
 * 
 * References:
 *         Morelli, R., & Walde, R. (2016). Java, Java, Java: Object-Oriented Problem Solving.
 *         Retrieved from
 *         https://open.umn.edu/opentextbooks/textbooks/java-java-java-object-oriented-problem-solving
 * 
 * 
 * Version/date: 29 April 2026
 * 
 * Responsibilities of class: 
 * 
 */

public class ScheduleGeneratorRepository
{
	List<Schedule> topThreeSchedules; // A schedule generator repository has-a list of the top three schedules
	
	
	
	// Constructor
	/**
	 * Purpose: To create a schedule generator repository object with default values
	 * 
	 */
	public ScheduleGeneratorRepository()
	{
		topThreeSchedules = null;
	}



	/**
	 * Purpose: To return the list of the top three schedules generated by the schedule generator
	 * @return topThreeSchedules The top 3 schedules
	 */
	public List<Schedule> getTopThreeSchedules()
	{
		return topThreeSchedules;
	}



	/**
	 * Purpose: To set the list of the top three schedules generated by the schedule generator
	 * @param newTopThreeSchedules
	 */
	public void addTopThreeSchedules(List<Schedule> newTopThreeSchedules)
	{
		topThreeSchedules = newTopThreeSchedules;
	}
}
	
	
	